const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d"),stats=document.getElementById("stats"),msg=document.getElementById("msg"),panel=document.getElementById("panel"),list=document.getElementById("inventoryList");
const products=[["blue_dream","ブルードリーム","weed",25],["gelato","ジェラート","weed",25],["og_haze","OGヘイズ","weed",25],["purple_haze","パープルヘイズ","weed",25],["azure_bloom","アズールブルーム","weed",25],["blood_ember","ブラッドエンバー","weed",25],["desert_drift","デザートドリフト","weed",25],["frostbyte","フロストバイト","weed",25],["glacier_dust","グレイシャーダスト","weed",25],["jungle_flame","ジャングルフレイム","weed",25],["shadow_nectar","シャドウネクター","weed",25],["sunset_kiss","サンセットキス","weed",25],["amber_shard","アンバーシャード","meth",45],["blue_sky","ブルースカイ","meth",45],["crystal","クリスタル","meth",45],["flash_gold","フラッシュゴールド","meth",45],["pure_rose","ピュアローズ","meth",45],["silent_mint","サイレントミント","meth",45],["blue_frost","ブルーフロスト","coke",60],["crack","クラック","coke",60],["cream_snow","クリームスノー","coke",60],["diamond_dust","ダイヤモンドダスト","coke",60],["pale_cut","ペイルカット","coke",60],["white_veil","ホワイトヴェイル","coke",60]].map(x=>({id:x[0],name:x[1],type:x[2],base:x[3]}));
const locations=[["safe_house","安全地帯","家",150,120,240,150],["gun_store","銃器店","店舗",900,90,160,110],["hardware","金物店","店舗",1080,90,170,110],["gas","ガスマート","店舗",1110,230,140,100],["pawn","質屋","店舗",900,240,150,100],["bank","銀行","店舗",700,240,150,100],["warehouse","倉庫","保管",100,470,250,170],["chemistry","化学ステーション","製造",470,470,190,150],["blending","混合ステーション","製造",690,470,190,150],["police","警察署","警察",1030,470,230,170]];
const S={day:1,min:480,money:500,suspicion:0,x:600,y:380,inside:null,inv:[{id:"blue_dream",q:5,price:30}],order:null};
function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener("resize",resize);resize();
function P(id){return products.find(p=>p.id===id)}
function say(t){msg.textContent=t;clearTimeout(say.t);say.t=setTimeout(()=>msg.textContent="",2500)}
function time(){return String(Math.floor(S.min/60)).padStart(2,"0")+":"+String(S.min%60).padStart(2,"0")}
function hud(){stats.textContent=`所持金 $${S.money}　手配度 ${S.suspicion}%　${S.day}日目　${time()}`+(S.order?`　注文: ${P(S.order.id).name} ×${S.order.q}`:"")}
function spawnOrder(){const p=products[Math.floor(Math.random()*products.length)],q=1+Math.floor(Math.random()*2);S.order={id:p.id,q,max:p.base+20+Math.floor(Math.random()*20),name:["ユウ","レン","カイ","ミナ"][Math.floor(Math.random()*4)]};say(`${S.order.name}から${p.name}の注文が入りました`);hud()}
function save(){localStorage.setItem("black-harvest-save",JSON.stringify(S));say("セーブしました")}
function load(){try{const x=JSON.parse(localStorage.getItem("black-harvest-save"));if(x)Object.assign(S,x)}catch{}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const sx=Math.max(0,Math.min(1400-canvas.width,S.x-canvas.width/2)),sy=Math.max(0,Math.min(760-canvas.height,S.y-canvas.height/2));ctx.save();ctx.translate(-sx,-sy);
ctx.fillStyle="#14171c";ctx.fillRect(0,0,1400,760);ctx.fillStyle="#292e37";ctx.fillRect(0,330,1400,90);ctx.fillRect(400,0,70,760);ctx.fillRect(850,0,70,760);
locations.forEach(l=>{ctx.fillStyle=l[2]==="警察"?"#30343b":l[2]==="製造"?"#2c3330":l[2]==="保管"?"#34302a":"#282d36";ctx.fillRect(l[3],l[4],l[5],l[6]);ctx.strokeStyle="#5c6674";ctx.strokeRect(l[3],l[4],l[5],l[6]);ctx.fillStyle="#f0f0f0";ctx.font="18px system-ui";ctx.fillText(l[1],l[3]+10,l[4]+27)});
ctx.fillStyle="#e4c967";ctx.fillRect(S.x-14,S.y-14,28,28);ctx.fillStyle="#fff";ctx.font="16px system-ui";ctx.fillText("プレイヤー",S.x-32,S.y-22);ctx.restore();hud();requestAnimationFrame(draw)}
const keys={};addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==="i")toggle();if(e.key.toLowerCase()==="e")interact();if(e.key===" ")advance(30)});addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);
function move(){if(panel.classList.contains("open"))return;let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(dx||dy){let n=Math.hypot(dx,dy);S.x=Math.max(15,Math.min(1385,S.x+dx/n*3));S.y=Math.max(15,Math.min(745,S.y+dy/n*3))}requestAnimationFrame(move)}move();
function near(){return locations.find(l=>Math.hypot(S.x-(l[3]+l[5]/2),S.y-(l[4]+l[6]/2))<Math.max(l[5],l[6])*.7)}
function interact(){if(S.inside){S.inside=null;say("街へ戻りました");return}const l=near();if(!l){say("近くに建物がありません");return}S.inside=l[0];say(`${l[1]}に入りました。Eで外へ戻れます`);if(l[2]==="警察")S.suspicion=Math.max(0,S.suspicion-10);hud()}
function toggle(){panel.classList.toggle("open");renderInv()}
function renderInv(){list.innerHTML="";S.inv.forEach(i=>{const p=P(i.id),r=document.createElement("div");r.className="row";const a=document.createElement("div");a.innerHTML=`<b>${p.name}</b><small>数量 ${i.q} / 売値 $${i.price}</small>`;const b=document.createElement("button");b.textContent="取引";b.onclick=()=>trade(i);const c=document.createElement("button");c.textContent="価格 +5";c.onclick=()=>{i.price+=5;renderInv()};r.append(a,c,b);list.append(r)});if(!S.inv.length)list.innerHTML="<p>商品がありません。</p>"}
function trade(i){if(!S.order){say("現在の注文がありません");return}if(i.id!==S.order.id){say("注文された商品ではありません");return}if(i.q<S.order.q){say("数量が足りません");return}const total=i.price*S.order.q;if(i.price<=S.order.max){i.q-=S.order.q;S.money+=total;S.suspicion=Math.min(100,S.suspicion+S.order.q*5);say(`${S.order.name}との取引成立。$${total}を受け取りました`);S.order=null;spawnOrder()}else{const counter=Math.max(p.base,Math.floor((i.price+S.order.max)/2));if(counter<=S.order.max+5){i.price=counter;i.q-=S.order.q;S.money+=counter*S.order.q;S.suspicion=Math.min(100,S.suspicion+S.order.q*5);say(`価格交渉成立。$${counter*S.order.q}を受け取りました`);S.order=null;spawnOrder()}else say("価格が高すぎて断られました")};S.inv=S.inv.filter(x=>x.q>0);save();renderInv();hud()}
function advance(m){S.min+=m;S.suspicion=Math.max(0,S.suspicion-1);if(S.min>=1440){S.min=480;S.day++;S.suspicion=Math.max(0,S.suspicion-15);spawnOrder();say(`${S.day}日目が始まりました`)}if(S.min>=1380&&!S.inside){S.suspicion=Math.min(100,S.suspicion+5);say("門限です。安全地帯へ戻ってください")}hud()}
document.getElementById("inventory").onclick=toggle;document.getElementById("close").onclick=()=>panel.classList.remove("open");document.getElementById("save").onclick=save;document.getElementById("next").onclick=()=>advance(960);
document.querySelectorAll(".touch button").forEach(b=>b.addEventListener("pointerdown",()=>{S.x=Math.max(15,Math.min(1385,S.x+(Number(b.dataset.dx)||0)*35));S.y=Math.max(15,Math.min(745,S.y+(Number(b.dataset.dy)||0)*35))}));
load();if(!S.order)spawnOrder();draw();
